version: '2'
services:
    node:
        container_name: derebanda_node_1
        build:
            context: ./
            dockerfile: deploy/node.docker
        ports:
            - "3000:3000"
        volumes:
            - /media/d/OpenServer/domains/dereban.da/:/root/project
        tty: true
        environment:
            - "REDIS_PORT=6379"
            - "REDIS_HOST=cache"
            - "8025:8025"
